apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rhel9-vm-medium-template
  title: RHEL9 VM Medium Template
  description: creates a RHEL9 VM Medium
  tags:
    - rhel9-medium
    - vm
    - workshop
spec:
  owner: legacy-backend-team
  type: VM

  parameters:
    - title: Provide information about the GitHub location
      required:
        - org
      properties:
        org:
          title: GitHub Organization
          type: string
          description: Your GitHub organization
          default: virt-corp
    - title: Provide information about the new component
      required:
        - cluster_id
        - namespace
        - owner
      properties:
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.endor.codell.io
        namespace:
          title: Namespace
          type: string
          description: Namespace
          default: default
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: [User]
    - title: Provide Build Information
      required:
        - component_id
      properties:
        component_id:
          title: Component ID
          default: app-legacy
          type: string
          description: Comp Id
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          org: ${{parameters.org}}
          owner: ${{parameters.owner}}
          cluster_id: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.component_id}}
          repoName: ${{parameters.component_id}}
          user_id: ${{parameters.owner}}
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        description: RHEL9 VM Medium - ${{parameters.component_id}}
        repoUrl: github.com?owner=${{parameters.org}}&repo=${{parameters.component_id}}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public    
    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{parameters.component_id}}
          description: GitOps resources for ${{parameters.component_id}}
          destination: https://github.com/${{parameters.org}}/${{parameters.component_id}}-gitops.git
          source_repository: https://github.com/${{parameters.org}}/${{parameters.component_id}}.git
          repository_name: ${{parameters.component_id}}
          git_host: github.com
          org: ${{parameters.org}}
          cluster: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          user_id: ${{parameters.owner}}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=${{parameters.org}}&repo=${{parameters.component_id}}-gitops
        title: GitOps resources for ${{parameters.component_id}}
        description: GitOps deployment resources for ${{parameters.component_id}}
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.component_id}}-gitops
        argoInstance: endor-gitops
        namespace: ${{parameters.namespace}}
        repoUrl: https://github.com/${{parameters.org}}/${{parameters.component_id}}-gitops.git
        path: 'argocd/'
  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}

