apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: tomcat-vm-template
  title: Tomcat VM Template
  description: creates a Tomcat VM
  tags:
    - tomcat
    - vm
    - workshop
spec:
  owner: operations
  type: VM

  parameters:
    - title: Provide information about the GitHub location
      required:
        - group
        - host
      properties:
        host:
          title: Repo Host
          type: string
          description: Your SCM host
          default: github.com
        org:
          title: Repo Organization
          type: string
          description: Your SCM host organization/group
          default: virt-corp
    - title: Provide information about the new component
      required:
        - cluster_id
        - namespace
        - owner
      properties:
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.endor.codell.io
        namespace: 
          title: Namespace
          type: string
          description: Namespace
          default: virt-corp-userN
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: [User]
    - title: Provide Build Information
      required:
        - image_host
        - component_id
      properties:
        image_host:
          title: Data Source
          type: string
          description: Name of the DataSource to clone
          default: https://gpte-public.s3.amazonaws.com/ama_demo/tomcat-mad.qcow2
        component_id:
          title: NAME
          default: tomcat-vm-template
          type: string
          description: VM name
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          org: ${{parameters.org}}
          owner: default/${{parameters.owner}}
          cluster_id: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.component_id}}
          host: ${{ parameters.host }}
          repoName: ${{parameters.component_id}}
          user_id: ${{parameters.owner}}
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        description: ${{parameters.description}}
        repoUrl: github.com?owner=${{parameters.org}}&repo=${{parameters.component_id}}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public    
    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{parameters.component_id}}
          description: ${{parameters.description}}
          destination:  https://github.com/${{parameters.org}}/${{parameters.component_id}}-gitops.git
          source_repository: https://github.com/${{parameters.org}}/${{parameters.component_id}}.git
          repository_name: ${{parameters.component_id}}
          git_host: ${{ parameters.host }}
          org: ${{parameters.org}}
          cluster: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          image_host: ${{parameters.image_host}}/${{parameters.namespace}}
          image_name: ${{parameters.component_id}}
          user_id: ${{parameters.owner}}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=${{parameters.org}}&repo=${{parameters.component_id}}-gitops
        title: gitops resources for ${{parameters.namespace}}-gitops
        description: gitops resources for ${{parameters.namespace}}-gitops
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.component_id}}-gitops
        argoInstance: endor-gitops
        namespace: virt-corp
        repoUrl: https://github.com/${{parameters.org}}/${{parameters.component_id}}-gitops.git
        path: 'argocd/'
  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}

