---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{values.vm_name}}
  namespace: ${{values.namespace_id}}
  labels:
    app: ${{values.vm_name}}
    environment: ${{values.environment}}
spec:
  dataVolumeTemplates:
    - metadata:
        name: ${{values.vm_name}}-volume
      spec:
        sourceRef:
          kind: DataSource
          name: ${{values.os_image}}
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: ${{values.storage_size}}
  instancetype:
    name: ${{values.instance_type}}
  preference:
    name: ${{values.preference}}
  running: true
  template:
    metadata:
      labels:
        app: ${{values.vm_name}}
        environment: ${{values.environment}}
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
      volumes:
        - dataVolume:
            name: ${{values.vm_name}}-volume
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: cloud-user
              password: ${{values.vm_password}}
              chpasswd:
                expire: false
          name: cloudinitdisk
