---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{values.vm_name}}
  namespace: ${{values.namespace_id}}
  labels:
    app: ${{values.vm_name}}
    environment: ${{values.environment}}
    os-type: windows
spec:
  dataVolumeTemplates:
    - metadata:
        name: ${{values.vm_name}}-volume
      spec:
        sourceRef:
          kind: DataSource
          name: ${{values.os_version}}
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: ${{values.storage_size}}
  instancetype:
    name: ${{values.instance_type}}
  preference:
    name: ${{values.preference}}
  running: true
  template:
    metadata:
      labels:
        app: ${{values.vm_name}}
        environment: ${{values.environment}}
        os-type: windows
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - cdrom:
                bus: sata
              name: sysprep
          interfaces:
{%- for network in values.networks %}
  {%- if network == "pod" %}
            - name: podnet
              masquerade: {}
  {%- else %}
            - name: {{ network | replace("/", "-") }}
              bridge: {}
  {%- endif %}
{%- endfor %}
          tpm: {}
      networks:
{%- for network in values.networks %}
  {%- if network == "pod" %}
        - name: podnet
          pod: {}
  {%- else %}
    {%- set parts = network.split("/") %}
        - name: {{ network | replace("/", "-") }}
          multus:
            networkName: {{ parts[0] }}/{{ parts[1] }}
  {%- endif %}
{%- endfor %}
      volumes:
        - dataVolume:
            name: ${{values.vm_name}}-volume
          name: rootdisk
        - name: sysprep
          sysprep:
            configMap:
              name: ${{values.vm_name}}-sysprep
