---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.vm_name}}
  title: ${{values.vm_name}}
  description: Windows VM in ${{values.namespace_id}} namespace
  annotations:
    backstage.io/kubernetes-id: ${{values.vm_name}}
    backstage.io/kubernetes-namespace: ${{values.namespace_id}}
  tags:
    - vm
    - windows
    - ${{values.namespace_id}}
  links:
    - url: https://console-openshift-console.apps.endor.codell.io/k8s/ns/${{values.namespace_id}}/kubevirt.io~v1~VirtualMachine/${{values.vm_name}}
      title: View in OpenShift Console
      icon: dashboard
spec:
  type: vm
  lifecycle: ${{values.environment}}
  owner: user:default/guest
  system: virtualization
  subcomponentOf: component:default/${{values.namespace_id}}
